/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/_admin'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAdminAuditLogsRouteImport } from './routes/_app/_admin/audit-logs'
import { Route as AppAdminLogsRouteImport } from './routes/_app/_admin/logs'
import { Route as AppAdminUsersRouteImport } from './routes/_app/_admin/users'
import { Route as AppServersIndexRouteImport } from './routes/_app/servers/index'
import { Route as AppServersGuildIdRouteImport } from './routes/_app/servers/$guildId'
import { Route as AppServersGuildIdIndexRouteImport } from './routes/_app/servers/$guildId/index'
import { Route as AppServersGuildIdManageRouteImport } from './routes/_app/servers/$guildId/_manage'
import { Route as AppServersGuildIdLevelsRouteImport } from './routes/_app/servers/$guildId/levels'
import { Route as AppServersGuildIdManageAuditLogsRouteImport } from './routes/_app/servers/$guildId/_manage/audit-logs'
import { Route as AppServersGuildIdManageConfigRouteImport } from './routes/_app/servers/$guildId/_manage/config'
import { Route as AppServersGuildIdManageLogManagerRouteImport } from './routes/_app/servers/$guildId/_manage/log-manager'
import { Route as AppServersGuildIdManageNewsRouteImport } from './routes/_app/servers/$guildId/_manage/news'
import { Route as AppServersGuildIdManageOverviewRouteImport } from './routes/_app/servers/$guildId/_manage/overview'
import { Route as AppServersGuildIdManagePrBotRouteImport } from './routes/_app/servers/$guildId/_manage/pr-bot'
import { Route as AppServersGuildIdManageRoomAccessRouteImport } from './routes/_app/servers/$guildId/_manage/room-access'
import { Route as AppServersGuildIdManageVoiceGuardRouteImport } from './routes/_app/servers/$guildId/_manage/voice-guard'
import { Route as AppServersGuildIdManageWeatherRouteImport } from './routes/_app/servers/$guildId/_manage/weather'
import { Route as AppServersGuildIdManageWelcomeRouteImport } from './routes/_app/servers/$guildId/_manage/welcome'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditLogsRoute = AppAdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLogsRoute = AppAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppServersIndexRoute = AppServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => AppRoute,
} as any)
const AppServersGuildIdRoute = AppServersGuildIdRouteImport.update({
  id: '/servers/$guildId',
  path: '/servers/$guildId',
  getParentRoute: () => AppRoute,
} as any)
const AppServersGuildIdIndexRoute = AppServersGuildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppServersGuildIdRoute,
} as any)
const AppServersGuildIdManageRoute = AppServersGuildIdManageRouteImport.update({
  id: '/_manage',
  getParentRoute: () => AppServersGuildIdRoute,
} as any)
const AppServersGuildIdLevelsRoute = AppServersGuildIdLevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => AppServersGuildIdRoute,
} as any)
const AppServersGuildIdManageAuditLogsRoute =
  AppServersGuildIdManageAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AppServersGuildIdManageRoute,
  } as any)
const AppServersGuildIdManageConfigRoute =
  AppServersGuildIdManageConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AppServersGuildIdManageRoute,
  } as any)
const AppServersGuildIdManageLogManagerRoute =
  AppServersGuildIdManageLogManagerRouteImport.update({
    id: '/log-manager',
    path: '/log-manager',
    getParentRoute: () => AppServersGuildIdManageRoute,
  } as any)
const AppServersGuildIdManageNewsRoute =
  AppServersGuildIdManageNewsRouteImport.update({
    id: '/news',
    path: '/news',
    getParentRoute: () => AppServersGuildIdManageRoute,
  } as any)
const AppServersGuildIdManageOverviewRoute =
  AppServersGuildIdManageOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppServersGuildIdManageRoute,
  } as any)
const AppServersGuildIdManagePrBotRoute =
  AppServersGuildIdManagePrBotRouteImport.update({
    id: '/pr-bot',
    path: '/pr-bot',
    getParentRoute: () => AppServersGuildIdManageRoute,
  } as any)
const AppServersGuildIdManageRoomAccessRoute =
  AppServersGuildIdManageRoomAccessRouteImport.update({
    id: '/room-access',
    path: '/room-access',
    getParentRoute: () => AppServersGuildIdManageRoute,
  } as any)
const AppServersGuildIdManageVoiceGuardRoute =
  AppServersGuildIdManageVoiceGuardRouteImport.update({
    id: '/voice-guard',
    path: '/voice-guard',
    getParentRoute: () => AppServersGuildIdManageRoute,
  } as any)
const AppServersGuildIdManageWeatherRoute =
  AppServersGuildIdManageWeatherRouteImport.update({
    id: '/weather',
    path: '/weather',
    getParentRoute: () => AppServersGuildIdManageRoute,
  } as any)
const AppServersGuildIdManageWelcomeRoute =
  AppServersGuildIdManageWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => AppServersGuildIdManageRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/audit-logs': typeof AppAdminAuditLogsRoute
  '/logs': typeof AppAdminLogsRoute
  '/users': typeof AppAdminUsersRoute
  '/servers/$guildId': typeof AppServersGuildIdRouteWithChildren
  '/servers/': typeof AppServersIndexRoute
  '/servers/$guildId/levels': typeof AppServersGuildIdLevelsRoute
  '/servers/$guildId/': typeof AppServersGuildIdIndexRoute
  '/servers/$guildId/audit-logs': typeof AppServersGuildIdManageAuditLogsRoute
  '/servers/$guildId/config': typeof AppServersGuildIdManageConfigRoute
  '/servers/$guildId/log-manager': typeof AppServersGuildIdManageLogManagerRoute
  '/servers/$guildId/news': typeof AppServersGuildIdManageNewsRoute
  '/servers/$guildId/overview': typeof AppServersGuildIdManageOverviewRoute
  '/servers/$guildId/pr-bot': typeof AppServersGuildIdManagePrBotRoute
  '/servers/$guildId/room-access': typeof AppServersGuildIdManageRoomAccessRoute
  '/servers/$guildId/voice-guard': typeof AppServersGuildIdManageVoiceGuardRoute
  '/servers/$guildId/weather': typeof AppServersGuildIdManageWeatherRoute
  '/servers/$guildId/welcome': typeof AppServersGuildIdManageWelcomeRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/account': typeof AppAccountRoute
  '/audit-logs': typeof AppAdminAuditLogsRoute
  '/logs': typeof AppAdminLogsRoute
  '/users': typeof AppAdminUsersRoute
  '/servers': typeof AppServersIndexRoute
  '/servers/$guildId': typeof AppServersGuildIdIndexRoute
  '/servers/$guildId/levels': typeof AppServersGuildIdLevelsRoute
  '/servers/$guildId/audit-logs': typeof AppServersGuildIdManageAuditLogsRoute
  '/servers/$guildId/config': typeof AppServersGuildIdManageConfigRoute
  '/servers/$guildId/log-manager': typeof AppServersGuildIdManageLogManagerRoute
  '/servers/$guildId/news': typeof AppServersGuildIdManageNewsRoute
  '/servers/$guildId/overview': typeof AppServersGuildIdManageOverviewRoute
  '/servers/$guildId/pr-bot': typeof AppServersGuildIdManagePrBotRoute
  '/servers/$guildId/room-access': typeof AppServersGuildIdManageRoomAccessRoute
  '/servers/$guildId/voice-guard': typeof AppServersGuildIdManageVoiceGuardRoute
  '/servers/$guildId/weather': typeof AppServersGuildIdManageWeatherRoute
  '/servers/$guildId/welcome': typeof AppServersGuildIdManageWelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/_admin': typeof AppAdminRouteWithChildren
  '/_app/account': typeof AppAccountRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/_app/_admin/logs': typeof AppAdminLogsRoute
  '/_app/_admin/users': typeof AppAdminUsersRoute
  '/_app/servers/$guildId': typeof AppServersGuildIdRouteWithChildren
  '/_app/servers/': typeof AppServersIndexRoute
  '/_app/servers/$guildId/_manage': typeof AppServersGuildIdManageRouteWithChildren
  '/_app/servers/$guildId/levels': typeof AppServersGuildIdLevelsRoute
  '/_app/servers/$guildId/': typeof AppServersGuildIdIndexRoute
  '/_app/servers/$guildId/_manage/audit-logs': typeof AppServersGuildIdManageAuditLogsRoute
  '/_app/servers/$guildId/_manage/config': typeof AppServersGuildIdManageConfigRoute
  '/_app/servers/$guildId/_manage/log-manager': typeof AppServersGuildIdManageLogManagerRoute
  '/_app/servers/$guildId/_manage/news': typeof AppServersGuildIdManageNewsRoute
  '/_app/servers/$guildId/_manage/overview': typeof AppServersGuildIdManageOverviewRoute
  '/_app/servers/$guildId/_manage/pr-bot': typeof AppServersGuildIdManagePrBotRoute
  '/_app/servers/$guildId/_manage/room-access': typeof AppServersGuildIdManageRoomAccessRoute
  '/_app/servers/$guildId/_manage/voice-guard': typeof AppServersGuildIdManageVoiceGuardRoute
  '/_app/servers/$guildId/_manage/weather': typeof AppServersGuildIdManageWeatherRoute
  '/_app/servers/$guildId/_manage/welcome': typeof AppServersGuildIdManageWelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/audit-logs'
    | '/logs'
    | '/users'
    | '/servers/$guildId'
    | '/servers/'
    | '/servers/$guildId/levels'
    | '/servers/$guildId/'
    | '/servers/$guildId/audit-logs'
    | '/servers/$guildId/config'
    | '/servers/$guildId/log-manager'
    | '/servers/$guildId/news'
    | '/servers/$guildId/overview'
    | '/servers/$guildId/pr-bot'
    | '/servers/$guildId/room-access'
    | '/servers/$guildId/voice-guard'
    | '/servers/$guildId/weather'
    | '/servers/$guildId/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/account'
    | '/audit-logs'
    | '/logs'
    | '/users'
    | '/servers'
    | '/servers/$guildId'
    | '/servers/$guildId/levels'
    | '/servers/$guildId/audit-logs'
    | '/servers/$guildId/config'
    | '/servers/$guildId/log-manager'
    | '/servers/$guildId/news'
    | '/servers/$guildId/overview'
    | '/servers/$guildId/pr-bot'
    | '/servers/$guildId/room-access'
    | '/servers/$guildId/voice-guard'
    | '/servers/$guildId/weather'
    | '/servers/$guildId/welcome'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/_admin'
    | '/_app/account'
    | '/_app/'
    | '/_app/_admin/audit-logs'
    | '/_app/_admin/logs'
    | '/_app/_admin/users'
    | '/_app/servers/$guildId'
    | '/_app/servers/'
    | '/_app/servers/$guildId/_manage'
    | '/_app/servers/$guildId/levels'
    | '/_app/servers/$guildId/'
    | '/_app/servers/$guildId/_manage/audit-logs'
    | '/_app/servers/$guildId/_manage/config'
    | '/_app/servers/$guildId/_manage/log-manager'
    | '/_app/servers/$guildId/_manage/news'
    | '/_app/servers/$guildId/_manage/overview'
    | '/_app/servers/$guildId/_manage/pr-bot'
    | '/_app/servers/$guildId/_manage/room-access'
    | '/_app/servers/$guildId/_manage/voice-guard'
    | '/_app/servers/$guildId/_manage/weather'
    | '/_app/servers/$guildId/_manage/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_admin': {
      id: '/_app/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_admin/audit-logs': {
      id: '/_app/_admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAdminAuditLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/logs': {
      id: '/_app/_admin/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppAdminLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/users': {
      id: '/_app/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/servers/': {
      id: '/_app/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AppServersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers/$guildId': {
      id: '/_app/servers/$guildId'
      path: '/servers/$guildId'
      fullPath: '/servers/$guildId'
      preLoaderRoute: typeof AppServersGuildIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers/$guildId/': {
      id: '/_app/servers/$guildId/'
      path: '/'
      fullPath: '/servers/$guildId/'
      preLoaderRoute: typeof AppServersGuildIdIndexRouteImport
      parentRoute: typeof AppServersGuildIdRoute
    }
    '/_app/servers/$guildId/_manage': {
      id: '/_app/servers/$guildId/_manage'
      path: ''
      fullPath: '/servers/$guildId'
      preLoaderRoute: typeof AppServersGuildIdManageRouteImport
      parentRoute: typeof AppServersGuildIdRoute
    }
    '/_app/servers/$guildId/levels': {
      id: '/_app/servers/$guildId/levels'
      path: '/levels'
      fullPath: '/servers/$guildId/levels'
      preLoaderRoute: typeof AppServersGuildIdLevelsRouteImport
      parentRoute: typeof AppServersGuildIdRoute
    }
    '/_app/servers/$guildId/_manage/audit-logs': {
      id: '/_app/servers/$guildId/_manage/audit-logs'
      path: '/audit-logs'
      fullPath: '/servers/$guildId/audit-logs'
      preLoaderRoute: typeof AppServersGuildIdManageAuditLogsRouteImport
      parentRoute: typeof AppServersGuildIdManageRoute
    }
    '/_app/servers/$guildId/_manage/config': {
      id: '/_app/servers/$guildId/_manage/config'
      path: '/config'
      fullPath: '/servers/$guildId/config'
      preLoaderRoute: typeof AppServersGuildIdManageConfigRouteImport
      parentRoute: typeof AppServersGuildIdManageRoute
    }
    '/_app/servers/$guildId/_manage/log-manager': {
      id: '/_app/servers/$guildId/_manage/log-manager'
      path: '/log-manager'
      fullPath: '/servers/$guildId/log-manager'
      preLoaderRoute: typeof AppServersGuildIdManageLogManagerRouteImport
      parentRoute: typeof AppServersGuildIdManageRoute
    }
    '/_app/servers/$guildId/_manage/news': {
      id: '/_app/servers/$guildId/_manage/news'
      path: '/news'
      fullPath: '/servers/$guildId/news'
      preLoaderRoute: typeof AppServersGuildIdManageNewsRouteImport
      parentRoute: typeof AppServersGuildIdManageRoute
    }
    '/_app/servers/$guildId/_manage/overview': {
      id: '/_app/servers/$guildId/_manage/overview'
      path: '/overview'
      fullPath: '/servers/$guildId/overview'
      preLoaderRoute: typeof AppServersGuildIdManageOverviewRouteImport
      parentRoute: typeof AppServersGuildIdManageRoute
    }
    '/_app/servers/$guildId/_manage/pr-bot': {
      id: '/_app/servers/$guildId/_manage/pr-bot'
      path: '/pr-bot'
      fullPath: '/servers/$guildId/pr-bot'
      preLoaderRoute: typeof AppServersGuildIdManagePrBotRouteImport
      parentRoute: typeof AppServersGuildIdManageRoute
    }
    '/_app/servers/$guildId/_manage/room-access': {
      id: '/_app/servers/$guildId/_manage/room-access'
      path: '/room-access'
      fullPath: '/servers/$guildId/room-access'
      preLoaderRoute: typeof AppServersGuildIdManageRoomAccessRouteImport
      parentRoute: typeof AppServersGuildIdManageRoute
    }
    '/_app/servers/$guildId/_manage/voice-guard': {
      id: '/_app/servers/$guildId/_manage/voice-guard'
      path: '/voice-guard'
      fullPath: '/servers/$guildId/voice-guard'
      preLoaderRoute: typeof AppServersGuildIdManageVoiceGuardRouteImport
      parentRoute: typeof AppServersGuildIdManageRoute
    }
    '/_app/servers/$guildId/_manage/weather': {
      id: '/_app/servers/$guildId/_manage/weather'
      path: '/weather'
      fullPath: '/servers/$guildId/weather'
      preLoaderRoute: typeof AppServersGuildIdManageWeatherRouteImport
      parentRoute: typeof AppServersGuildIdManageRoute
    }
    '/_app/servers/$guildId/_manage/welcome': {
      id: '/_app/servers/$guildId/_manage/welcome'
      path: '/welcome'
      fullPath: '/servers/$guildId/welcome'
      preLoaderRoute: typeof AppServersGuildIdManageWelcomeRouteImport
      parentRoute: typeof AppServersGuildIdManageRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditLogsRoute: typeof AppAdminAuditLogsRoute
  AppAdminLogsRoute: typeof AppAdminLogsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditLogsRoute: AppAdminAuditLogsRoute,
  AppAdminLogsRoute: AppAdminLogsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppServersGuildIdManageRouteChildren {
  AppServersGuildIdManageAuditLogsRoute: typeof AppServersGuildIdManageAuditLogsRoute
  AppServersGuildIdManageConfigRoute: typeof AppServersGuildIdManageConfigRoute
  AppServersGuildIdManageLogManagerRoute: typeof AppServersGuildIdManageLogManagerRoute
  AppServersGuildIdManageNewsRoute: typeof AppServersGuildIdManageNewsRoute
  AppServersGuildIdManageOverviewRoute: typeof AppServersGuildIdManageOverviewRoute
  AppServersGuildIdManagePrBotRoute: typeof AppServersGuildIdManagePrBotRoute
  AppServersGuildIdManageRoomAccessRoute: typeof AppServersGuildIdManageRoomAccessRoute
  AppServersGuildIdManageVoiceGuardRoute: typeof AppServersGuildIdManageVoiceGuardRoute
  AppServersGuildIdManageWeatherRoute: typeof AppServersGuildIdManageWeatherRoute
  AppServersGuildIdManageWelcomeRoute: typeof AppServersGuildIdManageWelcomeRoute
}

const AppServersGuildIdManageRouteChildren: AppServersGuildIdManageRouteChildren =
  {
    AppServersGuildIdManageAuditLogsRoute:
      AppServersGuildIdManageAuditLogsRoute,
    AppServersGuildIdManageConfigRoute: AppServersGuildIdManageConfigRoute,
    AppServersGuildIdManageLogManagerRoute:
      AppServersGuildIdManageLogManagerRoute,
    AppServersGuildIdManageNewsRoute: AppServersGuildIdManageNewsRoute,
    AppServersGuildIdManageOverviewRoute: AppServersGuildIdManageOverviewRoute,
    AppServersGuildIdManagePrBotRoute: AppServersGuildIdManagePrBotRoute,
    AppServersGuildIdManageRoomAccessRoute:
      AppServersGuildIdManageRoomAccessRoute,
    AppServersGuildIdManageVoiceGuardRoute:
      AppServersGuildIdManageVoiceGuardRoute,
    AppServersGuildIdManageWeatherRoute: AppServersGuildIdManageWeatherRoute,
    AppServersGuildIdManageWelcomeRoute: AppServersGuildIdManageWelcomeRoute,
  }

const AppServersGuildIdManageRouteWithChildren =
  AppServersGuildIdManageRoute._addFileChildren(
    AppServersGuildIdManageRouteChildren,
  )

interface AppServersGuildIdRouteChildren {
  AppServersGuildIdManageRoute: typeof AppServersGuildIdManageRouteWithChildren
  AppServersGuildIdLevelsRoute: typeof AppServersGuildIdLevelsRoute
  AppServersGuildIdIndexRoute: typeof AppServersGuildIdIndexRoute
}

const AppServersGuildIdRouteChildren: AppServersGuildIdRouteChildren = {
  AppServersGuildIdManageRoute: AppServersGuildIdManageRouteWithChildren,
  AppServersGuildIdLevelsRoute: AppServersGuildIdLevelsRoute,
  AppServersGuildIdIndexRoute: AppServersGuildIdIndexRoute,
}

const AppServersGuildIdRouteWithChildren =
  AppServersGuildIdRoute._addFileChildren(AppServersGuildIdRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAccountRoute: typeof AppAccountRoute
  AppIndexRoute: typeof AppIndexRoute
  AppServersGuildIdRoute: typeof AppServersGuildIdRouteWithChildren
  AppServersIndexRoute: typeof AppServersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAccountRoute: AppAccountRoute,
  AppIndexRoute: AppIndexRoute,
  AppServersGuildIdRoute: AppServersGuildIdRouteWithChildren,
  AppServersIndexRoute: AppServersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
